### ISSUE TITLE
Add caliper events tracking in Runestone

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/RunestoneServer#5]
This is issue for tracking the overall progress of adding caliper events to Runestone. To complete this we'll have to finish the following (add more as they come up)

- [x] #2 Investigate events
- [x] #4 Investigate job scheduler
- [x] #10 Send events via caliper
- [x] #16 Caliper configuration via env
